Repository TEALSK12/2nd-semester-introduction-to-computer-science, pull requests merged in 2019-12, with the labels that each got.

#116 Andrew---11-26
  curriculum_map.md
Labels: Bug, Feature, IntroCS.2

#119 Andrew 12-10
  README.md
  SUMMARY.md
  curriculum_map.md
  readings.md
  units/1_unit/04_lesson/lesson.md
  units/1_unit/06_lesson/project.md
  units/1_unit/slidedecks/Intro Python 1.01 TEALS.pptx
  units/1_unit/slidedecks/Intro Python 1.02 TEALS.pptx
  units/1_unit/slidedecks/Intro Python 1.03 TEALS.pptx
  units/1_unit/slidedecks/Intro Python 1.04 TEALS.pptx
  units/1_unit/slidedecks/Intro Python 1.05 TEALS.pptx
  units/1_unit/slidedecks/Intro Python 1.06 TEALS.pptx
  units/1_unit/unit_1.md
  units/2_unit/04_lesson/lesson.md
  units/2_unit/05_lesson/lesson.md
  units/2_unit/unit2_md.md
  units/3_unit/unit_3.md
  units/4_unit/unit4.md
  units/6_unit/unit6.md
  units/7_unit/unit7.md
Labels: Bug, IntroCS.2

#120 Andrew 12 14
  Changelog.md
  README.md
  SUMMARY.md
  units/1_unit/03_lesson/lab.md
  units/1_unit/04_lesson/lesson.md
  units/1_unit/06_lesson/lesson.md
  units/2_unit/04_lesson/lesson.md
  units/2_unit/unit2_md.md
  units/3_unit/05_lesson/lesson.md
  units/3_unit/05_lesson/project.md
  units/3_unit/05_lesson/rubric.docx
  units/3_unit/05_lesson/rubric.md
  units/3_unit/05_lesson/rubric.pdf
  units/3_unit/unit_3.md
  units/4_unit/unit4.md
Labels: Bug, Feature, IntroCS.2

#121 Andrew-12-17
  README.md
  SUMMARY.md
  cert.md
  changelog.md
Labels: Bug, IntroCS.2

#122 2019 holiday break updates
  changelog.md
  curriculum_map.md
  units/1_unit/06_lesson/lesson.md
  units/1_unit/06_lesson/project.md
  units/2_unit/07_lesson/lesson.md
  units/2_unit/07_lesson/project.md
  units/2_unit/07_lesson/text_Monster_Starter_Code.py
  units/3_unit/05_lesson/Unit_3_Project_Oregon_Trail_Starter_Code.py
  units/3_unit/05_lesson/lesson.md
  units/3_unit/05_lesson/project.md
  units/4_unit/06_lesson/lesson.md
  units/4_unit/06_lesson/project.md
  units/4_unit/06_lesson/tictactoe_starter_code.py
  units/5_unit/05_lesson/lesson.md
  units/5_unit/05_lesson/project.md
  units/5_unit/05_lesson/rubric.docx
  units/5_unit/05_lesson/rubric.md
  units/5_unit/05_lesson/rubric.pdf
  units/6_unit/05_lesson/lesson.md
  units/6_unit/05_lesson/projectb.md
  units/7_unit/05_lesson/lesson.md
  units/7_unit/05_lesson/project.md
  units/8_unit/01_lesson/lesson.md
  units/8_unit/01_lesson/project_ideas.docx
  units/8_unit/01_lesson/project_ideas.md
  units/8_unit/01_lesson/project_ideas.pdf
  units/8_unit/project.md
  units/8_unit/unit8.md
Labels: Feature, IntroCS.2

#123 Brian projects
  units/1_unit/06_lesson/alternate_project.md
  units/2_unit/07_lesson/alternate_project.md
  units/3_unit/05_lesson/alternate_project.md
  units/4_unit/06_lesson/alternate_project.md
  units/7_unit/05_lesson/alternate_project.md
Labels: Feature, IntroCS.2
