Repository TEALSK12/2nd-semester-introduction-to-computer-science, pull requests merged in 2020-01, with the labels that each got.

#125 Update README.md
  README.md
Labels: Bug

#124 formatting changes
  .vscode/settings.json
  units/1_unit/01_lesson/lesson.docx
  units/1_unit/06_lesson/lesson.md
  units/2_unit/07_lesson/lesson.md
  units/6_unit/03_lesson/lab.docx
  units/8_unit/project.docx
Labels: Bug, IntroCS.2

#126 unit 6 slide decks
  changelog.md
  units/2_unit/unit2_md.md
  units/4_unit/slidedecks/Intro Python 4.01 TEALS.pptx
  units/4_unit/slidedecks/Intro Python 4.02 TEALS.pptx
  units/4_unit/slidedecks/Intro Python 4.03 TEALS.pptx
  units/6_unit/slidedecks/Intro Python 6.01 TEALS.pptx
  units/6_unit/slidedecks/Intro Python 6.02 TEALS.pptx
  units/6_unit/slidedecks/Intro Python 6.03 TEALS.pptx
  units/6_unit/slidedecks/Intro Python 6.04 TEALS.pptx
  units/6_unit/slidedecks/Intro Python 6.05 TEALS.pptx
Labels: Feature

#127 Ca 2019 tmp b
  curriculum_map.md
  units/2_unit/08_lesson/lesson.md
  units/2_unit/08_lesson/project_canada.md
  units/3_unit/05_lesson/lesson.md
  units/3_unit/05_lesson/project_canada.md
  units/4_unit/06_lesson/project_canada.md
Labels: Feature, IntroCS.2

#128 Case Updated to slide 1.03
  units/1_unit/slidedecks/Intro Python 1.03 TEALS.pptx
Labels: Bug, IntroCS.2
