Repository TEALSK12/2nd-semester-introduction-to-computer-science, pull requests merged in 2020-02, with the labels that each got.

#143 Unit 2 ppt update
  SUMMARY.md
  units/2_unit/slidedecks/Intro Python 2.01 TEALS.pptx
  units/2_unit/slidedecks/Intro Python 2.02 TEALS.pptx
  units/2_unit/slidedecks/Intro Python 2.03 TEALS.pptx
  units/2_unit/slidedecks/Intro Python 2.04 TEALS.pptx
  units/2_unit/slidedecks/Intro Python 2.05 TEALS.pptx
  units/2_unit/slidedecks/Intro Python 2.06 TEALS.pptx
  units/2_unit/slidedecks/Intro Python 2.07 TEALS.pptx
  units/3_unit/05_lesson/lesson.md
  units/3_unit/05_lesson/rubric.docx
  units/3_unit/05_lesson/rubric.md
  units/4_unit/06_lesson/lesson.md
  units/4_unit/06_lesson/rubric.docx
  units/4_unit/06_lesson/rubric.md
Labels: Feature, IntroCS.2

#144 Unit 6 Project Updates
  units/6_unit/05_lesson/lesson.md
  units/6_unit/05_lesson/rubric.docx
  units/6_unit/05_lesson/rubric.md
Labels: Feature

#146 Minor Working Changes
  SUMMARY.md
  changelog.md
  units/7_unit/05_lesson/rubric.md
Labels: Bug, IntroCS.2

#151 Issues #130 and #140
  units/2_unit/04_lesson/Starter_food_chooser.py
  units/2_unit/04_lesson/lab.docx
  units/2_unit/04_lesson/lab.md
  units/6_unit/04_lesson/do_now.md
  units/6_unit/04_lesson/lab.md
Labels: Bug

#152 Issue #131
  units/6_unit/04_lesson/lab.docx
  units/6_unit/04_lesson/lab.md
  units/6_unit/slidedecks/Intro Python 6.04 TEALS.pptx
Labels: Bug, IntroCS.2

#153 Updated Change Log
  changelog.md
Labels: Bug, IntroCS.2

#157 Unit 2 Project Behavior Update
  units/2_unit/07_lesson/project.md
Labels: Feature

#159 Updated point total
  units/6_unit/05_lesson/lesson.md
Labels: Bug, IntroCS.2

#158 Update total
  units/6_unit/05_lesson/rubric.md
Labels: Bug, IntroCS.2

#172 Updated Project Instructions from Volunteer Feedback
  units/2_unit/07_lesson/project.md
  units/3_unit/05_lesson/project.md
Labels: Bug, IntroCS.2

#176 Spelling and Formatting Updates Across Repo
  curriculum_map.md
  readings.md
  units/1_unit/02_lesson/lab.md
  units/1_unit/02_lesson/lesson.md
  units/1_unit/04_lesson/lab.md
  units/1_unit/04_lesson/lesson.md
  units/1_unit/05_lesson/alt1/README.md
  units/1_unit/05_lesson/lesson.md
  units/1_unit/06_lesson/alternate_project.md
  units/1_unit/06_lesson/lesson.md
  units/1_unit/06_lesson/project.md
  units/2_unit/01_lesson/lesson.md
  units/2_unit/02_lesson/lab.md
  units/2_unit/03_lesson/lesson.md
  units/2_unit/04_lesson/lesson.md
  units/2_unit/05_lesson/do_now2.md
  units/2_unit/05_lesson/lesson2.md
  units/2_unit/06_lesson/lab.md
  units/2_unit/06_lesson/lesson.md
  units/2_unit/07_lesson/alternate_project.md
  units/2_unit/07_lesson/lesson.md
  units/3_unit/04_lesson/do_now.md
  units/3_unit/04_lesson/lesson.md
  units/3_unit/05_lesson/alternate_project.md
  units/4_unit/01_lesson/lab.md
  units/4_unit/02_lesson/lab.md
  units/4_unit/02_lesson/lesson.md
  units/4_unit/04_lesson/lab.md
  units/4_unit/05_lesson/lab.md
  units/4_unit/06_lesson/project.md
  units/4_unit/unit4.md
  units/5_unit/01_lesson/lesson.md
  units/5_unit/02_lesson/lab.md
  units/5_unit/03_lesson/lab.md
  units/5_unit/03_lesson/lesson.md
  units/5_unit/04_lesson/lab.md
  units/5_unit/05_lesson/do_now.md
  units/5_unit/05_lesson/project.md
  units/5_unit/05_lesson/rubric.md
  units/6_unit/01_lesson/lesson.md
  units/6_unit/05_lesson/lesson.md
  units/6_unit/05_lesson/projectb.md
  units/6_unit/unit6.md
  units/7_unit/01_lesson/lesson.md
  units/7_unit/02_lesson/lesson.md
  units/7_unit/03_lesson/do_now.md
  units/7_unit/03_lesson/lab.md
  units/7_unit/03_lesson/lesson.md
  units/7_unit/04_lesson/lab.md
  units/7_unit/04_lesson/lesson.md
  units/7_unit/05_lesson/rubric.md
  units/7_unit/unit7.md
  units/8_unit/01_lesson/lesson.md
  units/8_unit/01_lesson/project_ideas.md
  units/8_unit/03_lesson/lesson.md
  units/8_unit/04_lesson/lesson.md
  units/8_unit/project.md
Labels: Bug, IntroCS.2
