Repository TEALSK12/2nd-semester-introduction-to-computer-science, pull requests merged in 2021-07, with the labels that each got.

#306 Added Link to Cross Country Canada Project Starter Code
  units/3_unit/05_lesson/lesson.md
Labels: Bug, IntroCS.2

#307 Issue 304 - Financial Calculator Project Update
  units/supplemental/calculator_canada.md
  units/supplemental/calculator_canada_project_spec.docx
  units/supplemental/calculator_canada_project_spec.pdf
Labels: IntroCS.2

#308 Financial Calculator project
  docs/units/3_unit/05_lesson/lesson.md.html
  docs/units/supplemental/calculator_canada.md.html
  docs/units/supplemental/calculator_canada_project_spec.docx
  docs/units/supplemental/calculator_canada_project_spec.pdf
Labels: Bug, Feature
